// Curated list of 5-letter answer words
export const ANSWERS: string[] = [
  'abbey', 'abhor', 'abide', 'abyss', 'acorn', 'acrid', 'actor', 'acute',
  'admit', 'adobe', 'adopt', 'adult', 'after', 'agate', 'agile', 'agony',
  'agree', 'ahead', 'aisle', 'alarm', 'album', 'alert', 'alien', 'align',
  'allay', 'alley', 'allot', 'allow', 'alone', 'along', 'aloof', 'aloud',
  'alpha', 'altar', 'alter', 'amber', 'amend', 'amiss', 'among', 'ample',
  'angel', 'angle', 'angry', 'annex', 'antic', 'anvil', 'aorta', 'apart',
  'apple', 'apply', 'apron', 'aptly', 'arbor', 'ardor', 'arena', 'arise',
  'armor', 'aroma', 'arose', 'arson', 'ashen', 'aside', 'askew', 'atoll',
  'atone', 'attic', 'audio', 'audit', 'avoid', 'awake', 'award', 'aware',
  'awash', 'awful', 'awoke', 'azure', 'badge', 'badly', 'bagel', 'baker',
  'banal', 'banjo', 'baron', 'basic', 'basil', 'basis', 'batch', 'bathe',
  'bayou', 'beach', 'beady', 'beard', 'beast', 'began', 'begin', 'being',
  'below', 'bench', 'berry', 'berth', 'bigot', 'bison', 'black', 'blade',
  'blame', 'bland', 'blank', 'blare', 'blast', 'blaze', 'bleak', 'bleat',
  'bleed', 'blend', 'bless', 'blind', 'bliss', 'block', 'bloom', 'blown',
  'blunt', 'blurb', 'blurt', 'blush', 'bogus', 'bonus', 'bosom', 'bound',
  'boxer', 'brash', 'brave', 'bravo', 'brawl', 'brawn', 'bread', 'break',
  'breed', 'briar', 'bride', 'brief', 'brine', 'brink', 'brisk', 'broad',
  'broke', 'brood', 'brook', 'broth', 'brown', 'brunt', 'brush', 'brute',
  'budge', 'built', 'bully', 'bunch', 'cabin', 'camel', 'canal', 'candy',
  'canny', 'canon', 'caper', 'carry', 'cause', 'cedar', 'cello', 'chair',
  'chalk', 'champ', 'chaos', 'charm', 'chart', 'chase', 'cheap', 'cheat',
  'cheek', 'chess', 'chest', 'chief', 'child', 'chili', 'chill', 'china',
  'choir', 'chord', 'chore', 'chose', 'chunk', 'civic', 'civil', 'claim',
  'clamp', 'clang', 'clash', 'clasp', 'class', 'cleat', 'cleft', 'clerk',
  'click', 'cliff', 'clink', 'cloak', 'clone', 'close', 'cloth', 'cloud',
  'clown', 'clunk', 'comet', 'comic', 'coral', 'couch', 'covet', 'crack',
  'craft', 'cramp', 'crane', 'creak', 'cream', 'credo', 'creek', 'creep',
  'crisp', 'cross', 'crown', 'cruel', 'crumb', 'crush', 'crust', 'crypt',
  'cubic', 'cyber', 'cycle', 'cynic', 'daisy', 'dance', 'datum', 'daunt',
  'dealt', 'death', 'debut', 'decoy', 'delta', 'demon', 'depot', 'depth',
  'derby', 'devil', 'ditty', 'divot', 'dizzy', 'dodge', 'douse', 'dowry',
  'draft', 'drain', 'drama', 'drank', 'drape', 'drawl', 'drawn', 'dregs',
  'dried', 'drift', 'drink', 'droop', 'drove', 'drown', 'drunk', 'dryer',
  'dunce', 'dwarf', 'dwell', 'eagle', 'earth', 'ebony', 'eight', 'elbow',
  'elite', 'ember', 'emote', 'empty', 'epoch', 'epoxy', 'equal', 'erode',
  'essay', 'ethos', 'evade', 'event', 'every', 'exact', 'exalt', 'exert',
  'extra', 'exult', 'fable', 'facet', 'faith', 'false', 'fancy', 'fatal',
  'fault', 'feast', 'feral', 'fetch', 'fever', 'flair', 'flake', 'flame',
  'flank', 'flare', 'flask', 'fleck', 'flesh', 'float', 'flock', 'flood',
  'floor', 'flour', 'flout', 'flown', 'fluff', 'fluke', 'flunk', 'flute',
  'flyer', 'focal', 'forge', 'forth', 'found', 'foxes', 'frail', 'frank',
  'fraud', 'freak', 'freed', 'fresh', 'frisk', 'frond', 'front', 'frost',
  'froze', 'fully', 'fungi', 'funky', 'funny', 'gauge', 'genre', 'ghost',
  'giant', 'given', 'gland', 'glare', 'glaze', 'gleam', 'glean', 'glint',
  'gloom', 'gloss', 'glove', 'glyph', 'gnome', 'going', 'gorge', 'gouge',
  'gourd', 'grace', 'grade', 'grain', 'grand', 'grant', 'grasp', 'grass',
  'grave', 'great', 'greed', 'greet', 'grief', 'groan', 'groom', 'gross',
  'grout', 'growl', 'grown', 'gruel', 'gruff', 'guard', 'guile', 'guise',
  'gulch', 'gusto', 'haiku', 'haunt', 'haven', 'hedge', 'heist', 'helix',
  'hence', 'herbs', 'hinge', 'hippo', 'hoard', 'hobby', 'honey', 'horse',
  'hotel', 'hover', 'human', 'humor', 'hurry', 'haste', 'ideal', 'idiom',
  'idyll', 'igloo', 'image', 'imply', 'inept', 'inert', 'infer', 'inner',
  'input', 'inter', 'intro', 'ionic', 'irate', 'irony', 'issue', 'ivory',
  'joker', 'jolly', 'joust', 'judge', 'juice', 'juicy', 'jumbo', 'jumpy',
  'knack', 'knave', 'kneel', 'knelt', 'knife', 'knock', 'knoll', 'known',
  'koala', 'kudos', 'label', 'lance', 'lapel', 'large', 'laser', 'latch',
  'latte', 'layer', 'leach', 'leafy', 'learn', 'lease', 'least', 'leech',
  'legal', 'lemon', 'level', 'light', 'lilac', 'liner', 'lingo', 'liver',
  'llama', 'lodge', 'logic', 'loose', 'lotus', 'lousy', 'lower', 'lucid',
  'lucky', 'lumen', 'lumpy', 'lunar', 'lunch', 'lyric', 'lapse', 'magic',
  'major', 'maker', 'manor', 'maple', 'match', 'maxim', 'mayor', 'mercy',
  'merit', 'messy', 'metal', 'might', 'milky', 'mimic', 'mirth', 'miser',
  'misty', 'mixed', 'model', 'money', 'month', 'moral', 'moose', 'mossy',
  'motif', 'motor', 'mourn', 'muddy', 'mural', 'murky', 'music', 'musty',
  'nadir', 'naive', 'nasty', 'naval', 'navel', 'nerve', 'never', 'nexus',
  'night', 'ninja', 'noble', 'noise', 'north', 'novel', 'nudge', 'nymph',
  'oasis', 'ocean', 'octet', 'olive', 'onset', 'optic', 'orbit', 'other',
  'otter', 'outer', 'oxide', 'ozone', 'panda', 'panic', 'papal', 'pasta',
  'patch', 'pause', 'peace', 'peach', 'pearl', 'pedal', 'penny', 'perch',
  'petty', 'phase', 'phone', 'photo', 'piano', 'pinch', 'pivot', 'pixel',
  'pizza', 'place', 'plain', 'plaid', 'plane', 'plank', 'plant', 'plaza',
  'plead', 'pluck', 'plumb', 'plume', 'plump', 'plunk', 'plush', 'poker',
  'polar', 'polka', 'poppy', 'pouch', 'pound', 'power', 'prank', 'press',
  'pride', 'prime', 'primp', 'prism', 'probe', 'prone', 'prong', 'prose',
  'proud', 'psalm', 'pupil', 'purge', 'pylon', 'proxy', 'queen', 'query',
  'quest', 'quick', 'quiet', 'quill', 'quota', 'quote', 'quake', 'rabbi',
  'rabid', 'radar', 'raspy', 'realm', 'rebel', 'reign', 'relax', 'repel',
  'resin', 'retro', 'rhyme', 'rider', 'rifle', 'right', 'rigid', 'risky',
  'rival', 'river', 'rivet', 'roast', 'robin', 'robot', 'rocky', 'rouge',
  'rough', 'rouse', 'round', 'route', 'royal', 'rugby', 'runny', 'rusty',
  'raven', 'reach', 'sadly', 'saint', 'salad', 'sauce', 'savvy', 'scalp',
  'scene', 'scone', 'scoop', 'scope', 'scout', 'scrap', 'screw', 'scrub',
  'seedy', 'sense', 'serum', 'seven', 'shaft', 'shake', 'shall', 'shame',
  'shark', 'sharp', 'sheep', 'sheer', 'sheet', 'shelf', 'shell', 'shift',
  'shine', 'shiny', 'shore', 'short', 'shout', 'shove', 'shrub', 'shrug',
  'siege', 'sigma', 'silly', 'since', 'sixth', 'sixty', 'skate', 'skill',
  'skimp', 'skirt', 'skunk', 'slash', 'slate', 'sleek', 'sleet', 'slept',
  'slice', 'slide', 'slime', 'sling', 'sloth', 'slump', 'slurp', 'small',
  'smear', 'smell', 'smelt', 'smirk', 'smite', 'smoke', 'snack', 'snail',
  'snare', 'sneak', 'sneer', 'snide', 'sniff', 'snore', 'snort', 'solar',
  'solid', 'solve', 'sonic', 'sorry', 'south', 'space', 'spade', 'spark',
  'spawn', 'speak', 'spear', 'speck', 'spice', 'spike', 'spill', 'spine',
  'spire', 'spite', 'spoke', 'spook', 'spoon', 'sport', 'spout', 'spray',
  'spree', 'spunk', 'squad', 'squat', 'squid', 'stack', 'staff', 'stain',
  'stair', 'stake', 'stale', 'stall', 'stank', 'stare', 'stark', 'start',
  'stash', 'state', 'stave', 'stead', 'steam', 'steel', 'steep', 'steer',
  'stern', 'stiff', 'still', 'sting', 'stink', 'stock', 'stomp', 'stone',
  'stood', 'stool', 'storm', 'story', 'stout', 'stove', 'strap', 'straw',
  'stray', 'strip', 'strut', 'stuck', 'study', 'stuff', 'stump', 'stung',
  'stunk', 'stunt', 'style', 'suave', 'sugar', 'sunny', 'super', 'surge',
  'sushi', 'swamp', 'swarm', 'swear', 'sweat', 'sweep', 'sweet', 'swept',
  'swipe', 'swirl', 'swoon', 'synth', 'snout', 'taboo', 'tangy', 'tapir',
  'taunt', 'tawny', 'thank', 'theme', 'there', 'thick', 'think', 'third',
  'thorn', 'three', 'threw', 'throw', 'thrum', 'thump', 'tiara', 'tidal',
  'tiger', 'tilde', 'timid', 'tipsy', 'token', 'tonal', 'topic', 'total',
  'touch', 'tough', 'towel', 'toxic', 'trace', 'track', 'train', 'tramp',
  'trash', 'trawl', 'tread', 'trend', 'trial', 'tribe', 'trick', 'tripe',
  'troll', 'troop', 'trout', 'trove', 'truce', 'truck', 'trunk', 'tryst',
  'tuber', 'tulip', 'tunic', 'turbo', 'tutor', 'twang', 'tweed', 'tweet',
  'twirl', 'tabby', 'talon', 'tango', 'tardy', 'ultra', 'uncle', 'under',
  'unfit', 'union', 'unity', 'until', 'upper', 'usurp', 'utter', 'vague',
  'valid', 'valor', 'value', 'valve', 'vapid', 'vault', 'vaunt', 'visor',
  'vista', 'vixen', 'vodka', 'voter', 'vowel', 'venom', 'verse', 'vigor',
  'waist', 'waltz', 'watch', 'water', 'waver', 'weary', 'weave', 'wedge',
  'weird', 'whale', 'wheat', 'wheel', 'where', 'which', 'while', 'whiff',
  'whirl', 'whisk', 'white', 'whole', 'whose', 'widow', 'wield', 'wimpy',
  'winch', 'witch', 'women', 'world', 'worse', 'worst', 'worth', 'wrath',
  'wreak', 'wreck', 'wrest', 'wring', 'wrist', 'write', 'wrong', 'wrote',
  'yacht', 'yearn', 'yeast', 'yield', 'yokel', 'young', 'youth', 'zesty',
  'zippy', 'zonal', 'abbey', 'abbot', 'abide', 'afoot', 'afoul', 'aglow',
  'agave', 'ahead', 'aided', 'aimer', 'aired', 'alder', 'aloft', 'amble',
  'amply', 'annoy', 'aphid', 'aping', 'aptly', 'ardor', 'argon', 'array',
  'arson', 'ascot', 'askew', 'atlas', 'augur', 'avail', 'avant', 'avian',
  'avid',  'baize', 'baked', 'baler', 'barge', 'baron', 'baste', 'batty',
  'bawdy', 'beady', 'beige', 'belle', 'beset', 'bevel', 'bezel', 'biome',
  'birch', 'bloke', 'blurb', 'blaze', 'boggy', 'bolts', 'booze', 'boozy',
  'bored', 'botch', 'bough', 'brave', 'brawl', 'braze', 'burly', 'bushy',
  'butch', 'cabin', 'cadre', 'camel', 'cameo', 'carve', 'chafe', 'chant',
  'chasm', 'chive', 'cigar', 'cinch', 'cited', 'clove', 'cobra', 'coils',
  'colic', 'colon', 'corny', 'coven', 'covey', 'coyly', 'crass', 'crave',
  'crimp', 'croak', 'croon', 'cubic', 'cured', 'curry', 'cutie', 'cutsy',
  'daily', 'dally', 'dazed', 'debris', 'decal', 'decor', 'defer', 'demur',
  'depot', 'derby', 'digit', 'dimly', 'disco', 'ditch', 'doily', 'dowdy',
  'drawn', 'drool', 'dusty', 'dwelt', 'eager', 'early', 'eclat', 'edged',
  'eerie', 'eject', 'elder', 'embed', 'endow', 'enjoy', 'ensue', 'envoy',
  'equip', 'erect', 'evict', 'exile', 'expel', 'extol', 'faint', 'fairy',
  'false', 'fatty', 'fazed', 'felon', 'femur', 'fetid', 'fiend', 'fiery',
  'filth', 'finch', 'fired', 'flair', 'flare', 'flaxy', 'fleck', 'flick',
  'flint', 'flirt', 'flock', 'flung', 'foamy', 'foray', 'forte', 'found',
  'foyer', 'friar', 'frill', 'fritz', 'froze', 'frump', 'fudge', 'fugue',
  'furry', 'gaudy', 'gauze', 'gavel', 'gawky', 'giddy', 'gimpy', 'glean',
  'gloat', 'gloss', 'glyph', 'golly', 'gouge', 'grove', 'gruel', 'gusto',
  'gutsy', 'gypsy', 'hazel', 'heady', 'hefty', 'hence', 'hippy', 'hoary',
  'huffy', 'humid', 'hussy', 'hutch', 'hyena', 'jazzy', 'jelly', 'jerky',
  'jiffy', 'jimmy', 'jived', 'jokey', 'jolts', 'joust', 'jowly', 'juror',
  'jutty', 'kinky', 'knack', 'kooky', 'kitty', 'kneel', 'lathe', 'latte',
  'leaky', 'leafy', 'leapt', 'leery', 'lefty', 'leggy', 'lemur', 'liege',
  'light', 'lithe', 'livid', 'locus', 'lofty', 'loopy', 'lotto', 'lousy',
  'lumpy', 'lusty', 'lushy', 'lymph', 'maize', 'mambo', 'manly', 'manor',
  'mantle', 'mealy', 'melee', 'micro', 'milky', 'minty', 'mogul', 'moldy',
  'moody', 'mousy', 'muggy', 'myrrh', 'nanny', 'natty', 'nervy', 'niece',
  'nippy', 'nitty', 'noisy', 'nutty', 'oaken', 'odder', 'oddly', 'ovoid',
  'paddy', 'palsy', 'pansy', 'panty', 'pasty', 'patsy', 'patty', 'pawky',
  'peaky', 'pebby', 'peppy', 'perky', 'piney', 'pinky', 'pithy', 'piton',
  'plaid', 'plait', 'plait', 'plumb', 'podgy', 'porky', 'potty', 'pouty',
  'pricy', 'privy', 'primp', 'pudgy', 'puffy', 'pulpy', 'punky', 'pushy',
  'quaff', 'qualm', 'quill', 'queue', 'rainy', 'rampy', 'randy', 'reedy',
  'relay', 'remix', 'renew', 'repay', 'repel', 'retch', 'retry', 'rowdy',
  'ruddy', 'ruffy', 'runic', 'rushy', 'salty', 'sappy', 'saucy', 'seedy',
  'sevvy', 'shady', 'shaky', 'shawl', 'sissy', 'sixty', 'slimy', 'slimy',
  'slinky', 'smoggy', 'soggy', 'soppy', 'spiny', 'spool', 'spiky', 'spiny',
  'splay', 'spout', 'spray', 'spryly', 'stagy', 'staple', 'stony', 'stoic',
  'strewn', 'stuffy', 'sultry', 'sumac', 'tacky', 'tanky', 'tardy', 'tasty',
  'tatty', 'tawny', 'tepid', 'terse', 'testy', 'tippy', 'today', 'topsy',
  'tummy', 'tunny', 'turfy', 'twixt', 'udder', 'ulcer', 'umbra', 'unzip',
  'vaunt', 'venal', 'vibes', 'viral', 'vying', 'wacky', 'waddy', 'waded',
  'wispy', 'witty', 'woozy', 'wormy', 'wrack', 'wrung', 'yucky', 'yummy',
  'zappy', 'zebra', 'zilch',
].filter((w) => w.length === 5);

// De-duplicate
const seen = new Set<string>();
export const WORD_LIST: string[] = ANSWERS.filter((w) => {
  if (seen.has(w)) return false;
  seen.add(w);
  return true;
});

export function getDailyWord(): string {
  const start = new Date(2024, 0, 1).getTime();
  const now = new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate()).getTime();
  const dayIndex = Math.floor((today - start) / 86_400_000);
  return WORD_LIST[((dayIndex % WORD_LIST.length) + WORD_LIST.length) % WORD_LIST.length];
}

export function isValidWord(word: string): boolean {
  return word.length === 5 && /^[a-z]+$/.test(word) && WORD_LIST.includes(word);
}
